# Generated by Django 3.1.4 on 2021-01-10 22:41

import appExam.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id_exam', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('location', models.CharField(blank=True, default='8000', max_length=1000)),
                ('file_uploaded', models.FileField(blank=True, upload_to='file_uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_user', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('id_user', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_number', appExam.fields.IntegerRangeField()),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appExam.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appExam.student')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='student_id',
            field=models.ManyToManyField(blank=True, default='', to='appExam.Student'),
        ),
    ]
