# Generated by Django 3.1.4 on 2021-01-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appExam', '0002_auto_20210111_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='file_uploaded',
        ),
    ]
