version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/food_diary
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=exam_manager_dev
      - SQL_USER=exam_manager
      - SQL_PASSWORD=exam_manager123
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres

  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=exam_manager
      - POSTGRES_PASSWORD=exam_manager123
      - POSTGRES_DB=exam_manager_dev

volumes:
  postgres_data: